### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MemeMachineSO** [BionicCode/WpfFileExplorer#2]
Hi Bionic,

Sorry if I'm bothering you by opening an issue here. I also am creating a WPF File Explorer, but am experiencing a pretty strange bug. No one has been able to identify the cause, and I feel like I've tried just about everything. I am curious if you would be able to help, and what would be the best way to get in contact with you.

**Comment by BionicCode** [comment]
Hi MemeMachineSO,
Can you describe your problem, please?

Maybe this project can help you?
[BionicFileExplorer](https://github.com/BionicCode/BionicFileExplorer/tree/master/BionicFileExplorer)

**Comment by MemeMachineSO** [comment]
> Hi MemeMachineSO, Can you describe your problem, please?
> 
> Maybe this project can help you? [BionicFileExplorer](https://github.com/BionicCode/BionicFileExplorer/tree/master/BionicFileExplorer)

The problem has been fixed. If you're curious what it was, you can take a look here:
https://github.com/dotnet/wpf/issues/6909

Thanks for offering to help though :)

**Comment by MemeMachineSO** [comment]
Hi @BionicCode,

I recently thought of you when dealing with a WPF/MVVM issue that no one seems to be able to solve on SO. Maybe you will have some idea

Was curious about your take on this issue: https://stackoverflow.com/questions/75586402/treeview-relaycommand-does-not-execute-despite-breakpoint-hitting

Here is reproducible project: https://stackoverflow.com/questions/75586402/treeview-relaycommand-does-not-execute-despite-breakpoint-hitting

**Comment by BionicCode** [comment]
Hi,

I'm very sorry for being that late. This was not on purpose for sure.
I'm glad you found a solution. Good luck with your project.

Mit freundlichen Grüßen
Brian Sampoh

Mit freundlichen Grüßen
Brian Sampoh
________________________________
